### ISSUE TITLE
I am added on the queue but I cannot see it

### ISSUE THREAD

**Issue by minjil** [jburns20/q#4]
I am added on the queue, but I can't see that I am and the waiting time increases.

But I cannot add myself again, and the TA can see that I am on the list as well

**Comment by jburns20** [comment]
The queue uses your browser's cookies to keep track of who you are, so if you switched browsers, browser profiles, or used incognito/private mode, you won't be able to see your name on the queue. If this happens to you again, you can use the "log in" button at the top right to log into your Andrew account. After you log in, you'll be able to see your name on the queue.
